version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ride_allocation
    ports:
      - "5435:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
